In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7568, 5854, 432, 1477],
 [7568, 5854, 432, 4551],
 [7568, 9630, 432, 3607],
 [2993, 6214, 5784, 9469, 9684],
 [2993, 6214, 5784, 9469, 2014],
 [4047, 7568, 9110, 432, 1077],
 [73, 6929, 5521, 9469]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [25]:
import numpy as np

In [26]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7568 5854  432 1477]
 [   0    0    0    0 7568 5854  432 4551]
 [   0    0    0    0 7568 9630  432 3607]
 [   0    0    0 2993 6214 5784 9469 9684]
 [   0    0    0 2993 6214 5784 9469 2014]
 [   0    0    0 4047 7568 9110  432 1077]
 [   0    0    0    0   73 6929 5521 9469]]


In [19]:
## feature representation
dim=10

In [32]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [37]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (7, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step


array([[[ 0.01787451,  0.04075632, -0.04313667, -0.02808738,
         -0.02817326,  0.04079023,  0.03307401, -0.03037354,
         -0.04662713,  0.01523477],
        [ 0.01787451,  0.04075632, -0.04313667, -0.02808738,
         -0.02817326,  0.04079023,  0.03307401, -0.03037354,
         -0.04662713,  0.01523477],
        [ 0.01787451,  0.04075632, -0.04313667, -0.02808738,
         -0.02817326,  0.04079023,  0.03307401, -0.03037354,
         -0.04662713,  0.01523477],
        [ 0.01787451,  0.04075632, -0.04313667, -0.02808738,
         -0.02817326,  0.04079023,  0.03307401, -0.03037354,
         -0.04662713,  0.01523477],
        [-0.01201606,  0.01414626,  0.03860701,  0.01598797,
          0.04391552,  0.01895965,  0.03589279,  0.04442103,
         -0.00563138,  0.00528693],
        [-0.01244445, -0.02957804,  0.00261693,  0.02056589,
         -0.02634252,  0.00701339,  0.03048749, -0.02724193,
         -0.02480011, -0.02679308],
        [-0.0077255 ,  0.02052528,  0.00756169,  0.0

In [55]:
input_data = np.array(embedded_docs[0])
input_data

array([   0,    0,    0,    0, 7568, 5854,  432, 1477])

In [56]:
input_data = input_data.reshape(1, input_data.shape[0]) 

In [57]:
predictions = model.predict(input_data)
predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step


array([[[ 0.01787451,  0.04075632, -0.04313667, -0.02808738,
         -0.02817326,  0.04079023,  0.03307401, -0.03037354,
         -0.04662713,  0.01523477],
        [ 0.01787451,  0.04075632, -0.04313667, -0.02808738,
         -0.02817326,  0.04079023,  0.03307401, -0.03037354,
         -0.04662713,  0.01523477],
        [ 0.01787451,  0.04075632, -0.04313667, -0.02808738,
         -0.02817326,  0.04079023,  0.03307401, -0.03037354,
         -0.04662713,  0.01523477],
        [ 0.01787451,  0.04075632, -0.04313667, -0.02808738,
         -0.02817326,  0.04079023,  0.03307401, -0.03037354,
         -0.04662713,  0.01523477],
        [-0.01201606,  0.01414626,  0.03860701,  0.01598797,
          0.04391552,  0.01895965,  0.03589279,  0.04442103,
         -0.00563138,  0.00528693],
        [-0.01244445, -0.02957804,  0.00261693,  0.02056589,
         -0.02634252,  0.00701339,  0.03048749, -0.02724193,
         -0.02480011, -0.02679308],
        [-0.0077255 ,  0.02052528,  0.00756169,  0.0